version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://fmeca:password@postgres:5432/fmeca?sslmode=disable
      - SESSION_SECRET=your-super-secret-session-key-change-this-in-production
      - APP_BASE_URL=http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./storage:/app/storage

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fmeca
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fmeca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fmeca"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
